# required for docker
sudo: required
language: python
python:
    - "3.6"
services:
  - docker
script:
  - docker build --tag myimage .
  - docker run -p 5000:5000 myimage pytest # or py.test for Python versions 3.5 and below
