version: "3"

services:
  web:
    build: ./web
    volumes:
      - ./web:/code
    command: ["python", "wsgi.py"]
    # command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "wsgi:app"]
    ports:
      - "5000:5000"
